// <auto-generated />
using System;
using CashFlowArchitecture.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashFlowArchitecture.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CashFlowDbContext))]
    [Migration("20260901205937_InitialPostgresSchema")]
    partial class InitialPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashFlowArchitecture.Api.Infrastructure.Persistence.DailyBalanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BalanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalCredits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDebits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BalanceDate")
                        .IsUnique();

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("daily_balances", (string)null);
                });

            modelBuilder.Entity("CashFlowArchitecture.Api.Infrastructure.Persistence.DailyBalanceProcessedEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DailyBalanceId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EventUid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DailyBalanceId");

                    b.HasIndex("EventUid")
                        .IsUnique();

                    b.ToTable("daily_balance_processed_events", (string)null);
                });

            modelBuilder.Entity("CashFlowArchitecture.Api.Infrastructure.Persistence.FinancialEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("financial_entries", (string)null);
                });

            modelBuilder.Entity("CashFlowArchitecture.Api.Infrastructure.Persistence.DailyBalanceProcessedEventEntity", b =>
                {
                    b.HasOne("CashFlowArchitecture.Api.Infrastructure.Persistence.DailyBalanceEntity", "DailyBalance")
                        .WithMany("ProcessedEvents")
                        .HasForeignKey("DailyBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyBalance");
                });

            modelBuilder.Entity("CashFlowArchitecture.Api.Infrastructure.Persistence.DailyBalanceEntity", b =>
                {
                    b.Navigation("ProcessedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
