<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CashFlowArchitecture.Consolidation.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CashFlowArchitecture.Core/CashFlowArchitecture.Core.csproj" />
    <ProjectReference Include="../CashFlowArchitecture.Infrastructure/CashFlowArchitecture.Infrastructure.csproj" />
  </ItemGroup>
</Project>
